### ISSUE TITLE
Refresh Page with Browser Refresh Button

### ISSUE THREAD

**Issue by AndrewPaget** [scssyworks/jqueryrouter#13]
I am testing this plugin and note, when using the browser refresh to refresh the page, only the ajax part of the page shows?

Is there a method for stopping this. I have gone through the docs and see no resolve for this?

**Comment by scssyworks** [comment]
Hi Andrew,
Can you please throw some light on the exact issue you are facing? Some sample code would be helpful in order to debug this issue further.
Apologies for a late reply!
Thanks
Sachin

**Comment by scssyworks** [comment]
Hi Andrew,
I am closing this issue. Please feel free to open another issue if you think your problem is still not resolved.
